In [37]:
import pandas as pd
from pathlib import Path
from property_prediction.dataset import get_db_connection
from dotenv import dotenv_values
from matminer.featurizers.conversions import StrToComposition
from matminer.featurizers.composition import ElementProperty

pd.set_option('display.max_columns', 200)

In [53]:
ROOT = Path().resolve().parent
config = dotenv_values(ROOT / '.env')
conn = get_db_connection(config)
db_name = 'materials'

sql = f"SELECT * from {db_name}"
raw_materials_df = pd.read_sql(sql, conn)

/var/folders/d2/yjlrc0dj6vddrg18pb4b2v3h0000gn/T/ipykernel_53199/2008374035.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  raw_materials_df = pd.read_sql(sql, conn)

In [28]:
formulas_df = raw_materials_df[['formula_pretty']]
formulas_df = formulas_df.drop_duplicates(subset='formula_pretty')
str_to_comp = StrToComposition()
str_to_comp.set_n_jobs(8)

In [ ]:
processed_df = str_to_comp.featurize_dataframe(formulas_df, 'formula_pretty')

StrToComposition:   0%|          | 0/108121 [00:00<?, ?it/s]

                formula_pretty             composition
0                      LiGe2Ir            (Li, Ge, Ir)
1                         LiCl                (Li, Cl)
2                       LiFeO3             (Li, Fe, O)
3                      LiAl2Au            (Li, Al, Au)
4                      LiCuAu2            (Li, Cu, Au)
...                        ...                     ...
162718  Na30Ca4Nb20Si33(SO48)3  (Na, Ca, Nb, Si, S, O)
162719          NaY3TaP3(SO8)3    (Na, Y, Ta, P, S, O)
162720           Na4ZrSi3GeO12     (Na, Zr, Si, Ge, O)
162721       Na3ScSi3Ge3(SO8)3  (Na, Sc, Si, Ge, S, O)
162722       Na10Y2Ta6Si11SO48   (Na, Y, Ta, Si, S, O)

[108121 rows x 2 columns]

In [35]:
ep = ElementProperty.from_preset(preset_name='magpie')
ep.set_n_jobs(8)
comp = processed_df.iloc[0,1]
features_df = ep.featurize_dataframe(processed_df, 'composition')

ElementProperty:   0%|          | 0/108121 [00:00<?, ?it/s]

In [ ]:
merged_df = raw_materials_df[['material_id', 'formula_pretty']].merge(features_df, on='formula_pretty').drop(columns=['formula_pretty'])

,material_id,MagpieData minimum Number,MagpieData maximum Number,MagpieData range Number,MagpieData mean Number,MagpieData avg_dev Number,MagpieData mode Number,MagpieData minimum MendeleevNumber,MagpieData maximum MendeleevNumber,MagpieData range MendeleevNumber,MagpieData mean MendeleevNumber,MagpieData avg_dev MendeleevNumber,MagpieData mode MendeleevNumber,MagpieData minimum AtomicWeight,MagpieData maximum AtomicWeight,MagpieData range AtomicWeight,MagpieData mean AtomicWeight,MagpieData avg_dev AtomicWeight,MagpieData mode AtomicWeight,MagpieData minimum MeltingT,MagpieData maximum MeltingT,MagpieData range MeltingT,MagpieData mean MeltingT,MagpieData avg_dev MeltingT,MagpieData mode MeltingT,MagpieData minimum Column,MagpieData maximum Column,MagpieData range Column,MagpieData mean Column,MagpieData avg_dev Column,MagpieData mode Column,MagpieData minimum Row,MagpieData maximum Row,MagpieData range Row,MagpieData mean Row,MagpieData avg_dev Row,MagpieData mode Row,MagpieData minimum CovalentRadius,MagpieData maximum CovalentRadius,MagpieData range CovalentRadius,MagpieData mean CovalentRadius,MagpieData avg_dev CovalentRadius,MagpieData mode CovalentRadius,MagpieData minimum Electronegativity,MagpieData maximum Electronegativity,MagpieData range Electronegativity,MagpieData mean Electronegativity,MagpieData avg_dev Electronegativity,MagpieData mode Electronegativity,MagpieData minimum NsValence,MagpieData maximum NsValence,MagpieData range NsValence,MagpieData mean NsValence,MagpieData avg_dev NsValence,MagpieData mode NsValence,MagpieData minimum NpValence,MagpieData maximum NpValence,MagpieData range NpValence,MagpieData mean NpValence,MagpieData avg_dev NpValence,MagpieData mode NpValence,MagpieData minimum NdValence,MagpieData maximum NdValence,MagpieData range NdValence,MagpieData mean NdValence,MagpieData avg_dev NdValence,MagpieData mode NdValence,MagpieData minimum NfValence,MagpieData maximum NfValence,MagpieData range NfValence,MagpieData mean NfValence,MagpieData avg_dev NfValence,MagpieData mode NfValence,MagpieData minimum NValence,MagpieData maximum NValence,MagpieData range NValence,MagpieData mean NValence,MagpieData avg_dev NValence,MagpieData mode NValence,MagpieData minimum NsUnfilled,MagpieData maximum NsUnfilled,MagpieData range NsUnfilled,MagpieData mean NsUnfilled,MagpieData avg_dev NsUnfilled,MagpieData mode NsUnfilled,MagpieData minimum NpUnfilled,MagpieData maximum NpUnfilled,MagpieData range NpUnfilled,MagpieData mean NpUnfilled,MagpieData avg_dev NpUnfilled,MagpieData mode NpUnfilled,MagpieData minimum NdUnfilled,MagpieData maximum NdUnfilled,MagpieData range NdUnfilled,MagpieData mean NdUnfilled,MagpieData avg_dev NdUnfilled,MagpieData mode NdUnfilled,MagpieData minimum NfUnfilled,MagpieData maximum NfUnfilled,MagpieData range NfUnfilled,MagpieData mean NfUnfilled,MagpieData avg_dev NfUnfilled,MagpieData mode NfUnfilled,MagpieData minimum NUnfilled,MagpieData maximum NUnfilled,MagpieData range NUnfilled,MagpieData mean NUnfilled,MagpieData avg_dev NUnfilled,MagpieData mode NUnfilled,MagpieData minimum GSvolume_pa,MagpieData maximum GSvolume_pa,MagpieData range GSvolume_pa,MagpieData mean GSvolume_pa,MagpieData avg_dev GSvolume_pa,MagpieData mode GSvolume_pa,MagpieData minimum GSbandgap,MagpieData maximum GSbandgap,MagpieData range GSbandgap,MagpieData mean GSbandgap,MagpieData avg_dev GSbandgap,MagpieData mode GSbandgap,MagpieData minimum GSmagmom,MagpieData maximum GSmagmom,MagpieData range GSmagmom,MagpieData mean GSmagmom,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber
0,mp-1185318,3.0,77.0,74.0,36.000000,20.500000,32.0,1.0,79.0,78.0,54.750000,26.875000,79.0,6.94100,192.217000,185.276000,86.109500,53.053750,72.640000,453.69,2739.00,2285.31,1403.872500,667.563750,1211.40,1.0,14.0,13.0,9.500000,4.500000,14.0,2.0,6.0,4.0,4.000000,1.000000,4.0,120.0,141.0,21.0,127.250000,7.250000,120.0,0.98,2.20,1.22,1.800000,0.410000,2.01,1.0,2.0,1.0,1.750000,0.375000,2.0,0.0,2.0,2.0,1.000000,1.000000,2.0,0.0,10.0,10.0,6.750000,3.375000,10.0,0.0,14.0,14.0,3.5,5.25,0.0,1.0,23.0,22.0,13.000000,6.000000,14.0,0.0,1.0,1.0,0.250000,0.375000,0.0,0.0,4.0,4.0,2.000000,2.000000,4.0,0.0,3.0,3.0,0.750000,1.125000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0,3.0,3.000000,1.000000,4.0,14.210000,23.005000,8.795000,19.203333,3.801667,23.005000,0.0,0.383,0.383,0.191500,0.191500,0.383,0.0,0.000000,0.000000,0.000000,0.000000,0.0,225.0,229.0,4.0,226.000000,1.500000,225.0
1,mp-1185319,3.0,17.0,14.0,10.000000,7.000000,3.0,1.0,94.0,93.0,47.500000,46.500000,1.0,6.94100,35.453000,28.512000,21.197000,14.256000,6.941000,171.60,453.69,282.09,312.645000,141.045000,171.60,1.0,17.0,16.0,9.000000,8.000000,1.0,2.0,3.0,1.0,2.500000,0.500000,2.0,102.0,128.0,26.0,115.000000,13.000000,102.0,0.98,3.16,2.18,2.070000,1.090000,0.98,1.0,2.0,1.0,1.500000,0.500000,1.0,0.0,5.0,5.0,2.500000,2.500000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.00,0.0,1.0,7.0,6.0,4.000000,3.000000,1.0,0.0,1.0,1.0,0.500000,0.500000,0.0,0.0,1.0,1.0,0.500000,0.500000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.000000,0.000000,1.0,16.593333,24.497500,7.904167,20.545417,3.952083,16.593333,0.0,2.493,2.493,1.246500,1.246500,0.000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,64.0,229.0,165.0,146.500000,82.500000,64.0
2,mp-1185320,3.0,26.0,23.0,10.600000,6.160000,8.0,1.0,87.0,86.0,63.400000,28.320000,87.0,6.94100,55.845000,48.904000,22.156840,13.475264,15.999400,54.80,1811.00,1756.20,485.818000,530.072800,54.80,1.0,16.0,15.0,11.400000,5.520000,16.0,2.0,4.0,2.0,2.400000,0.640000,2.0,66.0,132.0,66.0,91.600000,30.720000,66.0,0.98,3.44,2.46,2.626000,0.976800,3.44,1.0,2.0,1.0,1.800000,0.320000,2.0,0.0,4.0,4.0,2.400000,1.920000,4.0,0.0,6.0,6.0,1.200000,1.920000,0.0,0.0,0.0,0.0,0.0,0.00,0.0,1.0,8.0,7.0,5.400000,1.760000,6.0,0.0,1.0,1.0,0.200000,0.320000,0.0,0.0,2.0,2.0,1.200000,0.960000,2.0,0.0,4.0,4.0,0.800000,1.280000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0,3.0,2.200000,0.720000,2.0,9.105000,16.593333,7.488333,10.927667,2.266267,9.105000,0.0,0.000,0.000,0.000000,0.000000,0.000,0.0,2.110663,2.110663,0.422133,0.675412,0.0,12.0,229.0,217.0,98.800000,104.160000,12.0
3,mp-1185321,3.0,79.0,76.0,27.000000,26.000000,13.0,1.0,73.0,72.0,53.250000,26.125000,73.0,6.94100,196.966569,190.025569,64.467662,66.249454,26.981539,453.69,1337.33,883.64,914.490000,230.400000,933.47,1.0,13.0,12.0,9.500000,4.250000,13.0,2.0,6.0,4.0,3.500000,1.250000,3.0,121.0,136.0,15.0,126.500000,5.500000,121.0,0.98,2.54,1.56,1.685000,0.427500,1.61,1.0,2.0,1.0,1.500000,0.500000,2.0,0.0,1.0,1.0,0.500000,0.500000,1.0,0.0,10.0,10.0,2.500000,3.750000,0.0,0.0,14.0,14.0,3.5,5.25,0.0,1.0,25.0,24.0,8.000000,8.500000,3.0,0.0,1.0,1.0,0.500000,0.500000,0.0,0.0,5.0,5.0,2.500000,2.500000,5.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,5.0,4.0,3.000000,2.000000,5.0,16.480000,16.700000,0.220000,16.563333,0.083333,16.480000,0.0,0.000,0.000,0.000000,0.000000,0.000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,225.0,229.0,4.0,226.000000,1.500000,225.0
4,mp-1185322,3.0,79.0,76.0,47.500000,31.500000,79.0,1.0,66.0,65.0,49.250000,24.125000,66.0,6.94100,196.966569,190.025569,116.105034,80.861535,196.966569,453.69,1357.77,904.08,1121.530000,333.920000,1337.33,1.0,11.0,10.0,8.500000,3.750000,11.0,2.0,6.0,4.0,4.500000,1.500000,6.0,128.0,136.0,8.0,133.000000,3.000000,136.0,0.98,2.54,1.56,1.990000,0.550000,2.54,1.0,1.0,0.0,1.000000,0.000000,1.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,10.0,10.0,7.500000,3.750000,10.0,0.0,14.0,14.0,7.0,7.00,14.0,1.0,25.0,24.0,15.500000,9.500000,25.0,1.0,1.0,0.0,1.000000,0.000000,1.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.000000,0.000000,1.0,11.070000,16.700000,5.630000,15.265833,2.097917,16.700000,0.0,0.000,0.000,0.000000,0.000000,0.000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,225.0,229.0,4.0,226.000000,1.500000,225.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163206,mp-2933374,1.0,55.0,54.0,14.909091,14.578512,8.0,5.0,92.0,87.0,71.181818,24.066116,87.0,1.00794,132.905452,131.897512,33.804108,36.036852,15.999400,14.01,3823.00,3808.99,777.381818,1107.497521,54.80,1.0,16.0,15.0,10.181818,6.677686,16.0,1.0,6.0,5.0,2.545455,1.256198,2.0,31.0,244.0,213.0,93.818182,54.611570,66.0,0.79,3.44,2.65,2.570909,0.790083,3.44,1.0,2.0,1.0,1.636364,0.462810,2.0,0.0,4.0,4.0,2.181818,1.652893,4.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.00,0.0,1.0,6.0,5.0,3.818182,2.049587,6.0,0.0,1.0,1.0,0.363636,0.462810,0.0,0.0,4.0,4.0,1.636364,1.190083,2.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0,3.0,2.000000,0.727273,2.0,5.640000,115.765000,110.125000,27.415000,32.127273,9.105000,0.0,7.853,7.853,2.245273,2.857620,0.000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,12.0,229.0,217.0,117.636364,96.033058,12.0
163207,mp-2933422,1.0,28.0,27.0,4.956522,4.128544,1.0,61.0,92.0,31.0,87.173913,5.035917,92.0,1.00794,58.693400,57.685460,9.514195,8.876092,1.007940,14.01,1728.00,1713.99,108.418261,140.833195,14.01,1.0,16.0,15.0,7.652174,6.941399,1.0,1.0,4.0,3.0,1.565217,0.589792,1.0,31.0,124.0,93.0,51.565217,21.459357,31.0,1.91,3.44,1.53,2.622174,0.502457,2.20,1.0,2.0,1.0,1.478261,0.499055,1.0,0.0,4.0,4.0,1.478261,1.671078,0.0,0.0,8.0,8.0,0.347826,0.665406,0.0,0.0,0.0,0.0,0.0,0.00,0.0,1.0,10.0,9.0,3.304348,2.404537,1.0,0.0,1.0,1.0,0.521739,0.499055,1.0,0.0,3.0,3.0,1.130435,1.277883,0.0,0.0,2.0,2.0,0.086957,0.166352,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,2.0,1.739130,0.771267,1.0,6.615000,14.768750,8.153750,9.336196,2.919924,6.615000,0.0,7.853,7.853,5.776435,2.511493,7.853,0.0,0.595395,0.595395,0.025887,0.049522,0.0,12.0,225.0,213.0,163.695652,52.763705,194.0
163208,mp-2933529,8.0,40.0,32.0,11.444444,4.308642,8.0,2.0,87.0,85.0,73.166667,19.055556,87.0,15.99940,91.224000,75.224600,23.641052,9.484527,15.999400,54.80,2128.00,2073.20,567.807778,670.773457,54.80,1.0,16.0,15.0,13.222222,3.740741,16.0,2.0,5.0,3.0,2.500000,0.611111,2.0,66.0,175.0,109.0,93.166667,33.203704,66.0,0.93,3.44,2.51,2.701667,0.902407,3.44,1.0,2.0,1.0,1.888889,0.197531,2.0,0.0,4.0,4.0,2.888889,1.358025,4.0,0.0,2.0,2.0,0.111111,0.209877,0.0,0.0,0.0,0.0,0.0,0.00,0.0,1.0,6.0,5.0,4.888889,1.358025,6.0,0.0,1.0,1.0,0.111111,0.197531,0.0,0.0,4.0,4.0,2.111111,0.839506,2.0,0.0,8.0,8.0,0.444444,0.839506,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,8.0,7.0,2.666667,1.185185,2.0,9.105000,29.243333,20.138333,14.644259,6.770206,9.105000,0.0,0.773,0.773,0.171778,0.267210,0.000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,12.0,229.0,217.0,94.000000,100.222222,12.0
163209,mp-2933735,8.0,29.0,21.0,15.000000,9.333333,8.0,64.0,87.0,23.0,79.333333,10.222222,87.0,15.99940,63.546000,47.546600,31.848267,21.131822,15.999400,54.80,1357.77,1302.97,489.123333,579.097778,54.80,11.0,16.0,5.0,14.333333,2.222222,16.0,2.0,4.0,2.0,2.666667,0.888889,2.0,66.0,132.0,66.0,88.000000,29.333333,66.0,1.90,3.44,1.54,2.926667,0.684444,3.44,1.0,2.0,1.0,1.666667,0.444444,2.0,0.0,4.0,4.0,2.666667,1.777778,4.0,0.0,10.0,10.0,3.333333,4.444444,0.0,0.0,0.0,0.0,0.0,0.00,0.0,6.0,11.0,5.0,7.666667,2.222222,6.0,0.0,1.0,1.0,0.333333,0.444444,0.0,0.0,2.0,2.0,1.333333,0.888889,2.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,1.0,1.666667,0.444444,2.0,9.105000,11.070000,1.965000,9.760000,0.873333,9.105000,0.0,0.000,0.000,0.000000,0.000000,0.000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,12.0,225.0,213.0,83.000000,94.666667,12.0
163210,mp-2936049,8.0,51.0,43.0,18.909091,13.884298,8.0,52.0,87.0,35.0,80.272727,10.280992,87.0,15.99940,121.760000,105.760600,42.308354,33.484123,15.999400,54.80,1519.00,1464.20,475.378182,535.281322,54.80,7.0,16.0,9.0,14.181818,2.611570,16.0,2.0,5.0,3.0,2.909091,1.157025,2.0,66.0,139.0,73.0,92.545455,33.785124,66.0,1.55,3.44,1.89,2.843636,0.759008,3.44,2.0,2.0,0.0,2.000000,0.000000,2.0,0.0,4.0,4.0,3.090909,1.157025,4.0,0.0,10.0,10.0,2.727273,3.471074,0.0,0.0,0.0,0.0,0.0,0.00,0.0,6.0,15.0,9.0,7.818182,2.611570,6.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,3.0,3.0,1.818182,0.661157,2.0,0.0,5.0,5.0,0.909091,1.487603,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,5.0,3.0,2.727273,0.925620,2.0,9.105000,31.560000,22.455000,13.439107,6.589416,9.105000,0.0,0.000,0.000,0.000000,0.000000,0.000,0.0,0.000310,0.000310,0.000056,0.000092,0.0,12.0,217.0,205.0,77.272727,83.074380,12.0

In [54]:
sql = """
    SELECT material_id, property_name, value
    from properties
    WHERE property_name IN ('band_gap', 'formation_energy_per_atom', 'bulk_modulus')
    AND value IS NOT NULL
"""
properties_df = pd.read_sql(sql, conn)

/var/folders/d2/yjlrc0dj6vddrg18pb4b2v3h0000gn/T/ipykernel_53199/2030557868.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  properties_df = pd.read_sql(sql, conn)

In [66]:
properties_pivot = properties_df.pivot_table(index='material_id', columns='property_name', values='value').reset_index()
final_df = merged_df.merge(properties_pivot, on='material_id', how='inner')
final_df.to_parquet('../data/processed/final_data.parquet')

In [ ]:
conn.close()